theme = "gruber_darker"

[editor]
line-number = "absolute"
# Activar formato automatico al guardar
auto-format = false
color-modes = true
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "separator", "file-base-name", "file-modification-indicator"]
center = ["spinner", "file-type", "read-only-indicator"]
right = ["diagnostics", "selections", "separator", "position", "position-percentage", "file-encoding"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "block"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true

[editor.soft-wrap]
# Activar el ajuste de línea
enable = true

[editor.inline-diagnostics]
cursor-line = "error"
